# Generated by Django 3.2.9 on 2022-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0005_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
