# Generated by Django 3.2.9 on 2022-01-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_clubs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=30)),
                ('companyname1', models.CharField(choices=[('Amazon', 'Amazon'), ('JPMC', 'JPMC'), ('Deloitte', 'Deloitte'), ('TCS', 'TCS'), ('Infosys', 'Infosys'), ('Wipro', 'Wipro'), ('Accenture', 'Accenture'), ('LTI', 'LTI'), ('Atlassian', 'Atlassian'), ('NCR', 'NCR'), ('Cognizant', 'Cognizant'), ('Factset', 'Factset'), ('Capgemini', 'Capgemini'), ('ACS', 'ACS'), ('Accolite', 'Accolite'), ('F5', 'F5'), ('StateStreet', 'StateStreet'), ('DBS', 'DBS'), ('Others', 'Others')], max_length=50)),
                ('companyname2', models.CharField(max_length=100)),
                ('question', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='sellform',
            name='category',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('JPMC', 'JPMC'), ('Deloitte', 'Deloitte'), ('TCS', 'TCS'), ('Infosys', 'Infosys'), ('Wipro', 'Wipro'), ('Accenture', 'Accenture'), ('LTI', 'LTI'), ('Atlassian', 'Atlassian'), ('NCR', 'NCR'), ('Cognizant', 'Cognizant'), ('Factset', 'Factset'), ('Capgemini', 'Capgemini'), ('ACS', 'ACS'), ('Accolite', 'Accolite'), ('F5', 'F5'), ('StateStreet', 'StateStreet'), ('DBS', 'DBS'), ('Others', 'Others')], max_length=15),
        ),
    ]
