# Generated by Django 3.2.9 on 2022-01-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20220102_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('student_username', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
