# Generated by Django 3.2.9 on 2022-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_answerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerform',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
