# Generated by Django 3.2.9 on 2022-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
            ],
        ),
    ]
