# Generated by Django 3.2.9 on 2022-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_techansform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='Sellform',
        ),
    ]
