# Generated by Django 3.2.9 on 2022-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vnr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupalumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('working', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('dateofjoining', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('worklocation', models.CharField(max_length=100)),
                ('company_name1', models.CharField(max_length=100)),
                ('company_name2', models.CharField(max_length=100)),
                ('company_name3', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Signupstudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
